[package]
name = "mq"
version = "0.4.4"
authors = ["Prabir Shrestha <mail@prabir.me>"]
edition = "2021"
license = "MIT"
description = "Simple Message Queue"
repository = "https://github.com/prabirshrestha/mq"
keywords = ["job", "scheduler", "queue"]

[dependencies]
async-trait = "0.1.68"
futures = "0.3.28"
serde = { version = "1.0.160", features = ["serde_derive"] }
serde_json = "1.0.95"
serde_with = "2.3.1"
thiserror = "1.0.31"
time = { version = "0.3.20", features = ["std", "serde", "parsing", "formatting"] }
tokio = { version = "1.27.0", features = ["macros", "time"] }
tokio-util = "0.7.7"
tracing = "0.1.37"
xid = "1.0.3"
