[package]
name = "mq"
version = "0.7.0"
authors = ["Prabir Shrestha <mail@prabir.me>"]
edition = "2021"
license = "MIT"
description = "Simple Message Queue"
repository = "https://github.com/prabirshrestha/mq"
keywords = ["job", "scheduler", "queue"]

[dependencies]
async-trait = "0.1.73"
futures = "0.3.28"
serde = { version = "1.0.189", features = ["serde_derive"] }
serde_json = "1.0.107"
serde_with = "3.3.0"
thiserror = "1.0.49"
time = { version = "0.3.30", features = ["std", "serde", "parsing", "formatting"] }
tokio = { version = "1.32.0", features = ["macros", "time"] }
tokio-util = "0.7.9"
tracing = "0.1.37"
xid = "1.0.3"
