[package]
name = "mq"
version = "0.4.8"
authors = ["Prabir Shrestha <mail@prabir.me>"]
edition = "2021"
license = "MIT"
description = "Simple Message Queue"
repository = "https://github.com/prabirshrestha/mq"
keywords = ["job", "scheduler", "queue"]

[dependencies]
async-trait = "0.1.71"
futures = "0.3.28"
serde = { version = "1.0.171", features = ["serde_derive"] }
serde_json = "1.0.100"
serde_with = "3.0.0"
thiserror = "1.0.43"
time = { version = "0.3.23", features = ["std", "serde", "parsing", "formatting"] }
tokio = { version = "1.29.1", features = ["macros", "time"] }
tokio-util = "0.7.8"
tracing = "0.1.37"
xid = "1.0.3"
