[package]
name = "mq-surreal"
version = "0.4.0"
edition = "2021"
authors = ["Prabir Shrestha <mail@prabir.me>"]
license = "MIT"
description = "Simple Message Queue for SurrealDB"
repository = "https://github.com/prabirshrestha/mq"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.68"
mq = { "path" = "../mq", version = "0.4.0" }
serde_json = "1.0.94"
surrealdb = { git = "https://github.com/surrealdb/surrealdb.git" }
time = { version = "0.3.20", features = ["std", "serde"] }
