[package]
name = "mq-surreal"
version = "0.4.8"
edition = "2021"
authors = ["Prabir Shrestha <mail@prabir.me>"]
license = "MIT"
description = "Simple Message Queue for SurrealDB"
repository = "https://github.com/prabirshrestha/mq"
keywords = ["job", "scheduler", "queue"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.72"
mq = { "path" = "../mq", version = "0.4.7" }
serde_json = "1.0.104"
surrealdb = "1.0.0-beta.9"
time = { version = "0.3.23", features = ["std", "serde"] }
